/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateRatingDto
 */
export interface CreateRatingDto {
    /**
     * 
     * @type {number}
     * @memberof CreateRatingDto
     */
    categoryId?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateRatingDto
     */
    rating?: number;
}

/**
 * Check if a given object implements the CreateRatingDto interface.
 */
export function instanceOfCreateRatingDto(value: object): boolean {
    return true;
}

export function CreateRatingDtoFromJSON(json: any): CreateRatingDto {
    return CreateRatingDtoFromJSONTyped(json, false);
}

export function CreateRatingDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRatingDto {
    if (json == null) {
        return json;
    }
    return {
        
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
        'rating': json['rating'] == null ? undefined : json['rating'],
    };
}

export function CreateRatingDtoToJSON(value?: CreateRatingDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'categoryId': value['categoryId'],
        'rating': value['rating'],
    };
}

