/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAuthZeroUserDto
 */
export interface CreateAuthZeroUserDto {
    /**
     * 
     * @type {string}
     * @memberof CreateAuthZeroUserDto
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAuthZeroUserDto
     */
    givenName?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAuthZeroUserDto
     */
    familyName?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAuthZeroUserDto
     */
    role?: CreateAuthZeroUserDtoRoleEnum;
    /**
     * 
     * @type {boolean}
     * @memberof CreateAuthZeroUserDto
     */
    blocked?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateAuthZeroUserDto
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAuthZeroUserDto
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAuthZeroUserDto
     */
    connection?: string;
}


/**
 * @export
 */
export const CreateAuthZeroUserDtoRoleEnum = {
    SocialWorker: 'SOCIAL_WORKER',
    Participant: 'PARTICIPANT',
    Admin: 'ADMIN',
    NoRole: 'NO_ROLE'
} as const;
export type CreateAuthZeroUserDtoRoleEnum = typeof CreateAuthZeroUserDtoRoleEnum[keyof typeof CreateAuthZeroUserDtoRoleEnum];


/**
 * Check if a given object implements the CreateAuthZeroUserDto interface.
 */
export function instanceOfCreateAuthZeroUserDto(value: object): boolean {
    return true;
}

export function CreateAuthZeroUserDtoFromJSON(json: any): CreateAuthZeroUserDto {
    return CreateAuthZeroUserDtoFromJSONTyped(json, false);
}

export function CreateAuthZeroUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAuthZeroUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'givenName': json['given_name'] == null ? undefined : json['given_name'],
        'familyName': json['family_name'] == null ? undefined : json['family_name'],
        'role': json['role'] == null ? undefined : json['role'],
        'blocked': json['blocked'] == null ? undefined : json['blocked'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'password': json['password'] == null ? undefined : json['password'],
        'connection': json['connection'] == null ? undefined : json['connection'],
    };
}

export function CreateAuthZeroUserDtoToJSON(value?: CreateAuthZeroUserDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'given_name': value['givenName'],
        'family_name': value['familyName'],
        'role': value['role'],
        'blocked': value['blocked'],
        'user_id': value['userId'],
        'password': value['password'],
        'connection': value['connection'],
    };
}

