#coverage:
#  status:
#    project:
#      default:
#        target: 70%
#        threshold: 5%
ignore:
  - "src/test/**/*"
  - "src/main/resources/**/*"
  - "src/main/java/ch/zhaw/pm4/compass/backend/model/dto/**/*"
  - "src/main/java/ch/zhaw/pm4/compass/backend/repository/**/*"
  - "src/main/java/ch/zhaw/pm4/compass/backend/exception/**/*"
