apiVersion: v1
kind: Service
metadata:
  name: compass
  labels:
    app: compass
spec:
  clusterIP: 10.43.111.111
  clusterIPs:
    - 10.43.111.111
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  type: ClusterIP
  ports:
    - name: nextjs
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: compass-app
status:
  loadBalancer: {}