apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-pvc
  namespace: compass-stage
spec:
  storageClassName: cinder-csi-ssd
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
