/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DaySheetDto,
  UpdateDaySheetDayNotesDto,
} from '../models/index';
import {
    DaySheetDtoFromJSON,
    DaySheetDtoToJSON,
    UpdateDaySheetDayNotesDtoFromJSON,
    UpdateDaySheetDayNotesDtoToJSON,
} from '../models/index';

export interface ConfirmRequest {
    id: number;
}

export interface CreateDaySheetRequest {
    daySheetDto: DaySheetDto;
}

export interface GetAllDaySheetByMonthRequest {
    month: string;
}

export interface GetAllDaySheetByParticipantAndMonthRequest {
    userId: string;
    month: string;
}

export interface GetDaySheetByIdRequest {
    id: number;
}

export interface GetDaySheetByParticipantAndDateRequest {
    userId: string;
    date: string;
}

export interface GetDaySheetDateRequest {
    date: string;
}

export interface RevokeRequest {
    id: number;
}

export interface UpdateDayNotesRequest {
    updateDaySheetDayNotesDto: UpdateDaySheetDayNotesDto;
}

/**
 * 
 */
export class DaySheetControllerApi extends runtime.BaseAPI {

    /**
     */
    async confirmRaw(requestParameters: ConfirmRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DaySheetDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling confirm().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/daysheet/confirm/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DaySheetDtoFromJSON(jsonValue));
    }

    /**
     */
    async confirm(requestParameters: ConfirmRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DaySheetDto> {
        const response = await this.confirmRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async createDaySheetRaw(requestParameters: CreateDaySheetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DaySheetDto>> {
        if (requestParameters['daySheetDto'] == null) {
            throw new runtime.RequiredError(
                'daySheetDto',
                'Required parameter "daySheetDto" was null or undefined when calling createDaySheet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/daysheet`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DaySheetDtoToJSON(requestParameters['daySheetDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DaySheetDtoFromJSON(jsonValue));
    }

    /**
     */
    async createDaySheet(requestParameters: CreateDaySheetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DaySheetDto> {
        const response = await this.createDaySheetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getAllDaySheetByMonthRaw(requestParameters: GetAllDaySheetByMonthRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DaySheetDto>>> {
        if (requestParameters['month'] == null) {
            throw new runtime.RequiredError(
                'month',
                'Required parameter "month" was null or undefined when calling getAllDaySheetByMonth().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/daysheet/getAllByMonth/{month}`.replace(`{${"month"}}`, encodeURIComponent(String(requestParameters['month']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DaySheetDtoFromJSON));
    }

    /**
     */
    async getAllDaySheetByMonth(requestParameters: GetAllDaySheetByMonthRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DaySheetDto>> {
        const response = await this.getAllDaySheetByMonthRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getAllDaySheetByParticipantAndMonthRaw(requestParameters: GetAllDaySheetByParticipantAndMonthRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DaySheetDto>>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getAllDaySheetByParticipantAndMonth().'
            );
        }

        if (requestParameters['month'] == null) {
            throw new runtime.RequiredError(
                'month',
                'Required parameter "month" was null or undefined when calling getAllDaySheetByParticipantAndMonth().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/daysheet/getAllByParticipantAndMonth/{userId}/{month}`.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))).replace(`{${"month"}}`, encodeURIComponent(String(requestParameters['month']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DaySheetDtoFromJSON));
    }

    /**
     */
    async getAllDaySheetByParticipantAndMonth(requestParameters: GetAllDaySheetByParticipantAndMonthRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DaySheetDto>> {
        const response = await this.getAllDaySheetByParticipantAndMonthRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getAllDaySheetNotConfirmedRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DaySheetDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/daysheet/getAllNotConfirmed`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DaySheetDtoFromJSON));
    }

    /**
     */
    async getAllDaySheetNotConfirmed(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DaySheetDto>> {
        const response = await this.getAllDaySheetNotConfirmedRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getDaySheetByIdRaw(requestParameters: GetDaySheetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DaySheetDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getDaySheetById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/daysheet/getById/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DaySheetDtoFromJSON(jsonValue));
    }

    /**
     */
    async getDaySheetById(requestParameters: GetDaySheetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DaySheetDto> {
        const response = await this.getDaySheetByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getDaySheetByParticipantAndDateRaw(requestParameters: GetDaySheetByParticipantAndDateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DaySheetDto>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getDaySheetByParticipantAndDate().'
            );
        }

        if (requestParameters['date'] == null) {
            throw new runtime.RequiredError(
                'date',
                'Required parameter "date" was null or undefined when calling getDaySheetByParticipantAndDate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/daysheet/getByParticipantAndDate/{userId}/{date}`.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))).replace(`{${"date"}}`, encodeURIComponent(String(requestParameters['date']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DaySheetDtoFromJSON(jsonValue));
    }

    /**
     */
    async getDaySheetByParticipantAndDate(requestParameters: GetDaySheetByParticipantAndDateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DaySheetDto> {
        const response = await this.getDaySheetByParticipantAndDateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getDaySheetDateRaw(requestParameters: GetDaySheetDateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DaySheetDto>> {
        if (requestParameters['date'] == null) {
            throw new runtime.RequiredError(
                'date',
                'Required parameter "date" was null or undefined when calling getDaySheetDate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/daysheet/getByDate/{date}`.replace(`{${"date"}}`, encodeURIComponent(String(requestParameters['date']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DaySheetDtoFromJSON(jsonValue));
    }

    /**
     */
    async getDaySheetDate(requestParameters: GetDaySheetDateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DaySheetDto> {
        const response = await this.getDaySheetDateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async revokeRaw(requestParameters: RevokeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DaySheetDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling revoke().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/daysheet/revoke/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DaySheetDtoFromJSON(jsonValue));
    }

    /**
     */
    async revoke(requestParameters: RevokeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DaySheetDto> {
        const response = await this.revokeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateDayNotesRaw(requestParameters: UpdateDayNotesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DaySheetDto>> {
        if (requestParameters['updateDaySheetDayNotesDto'] == null) {
            throw new runtime.RequiredError(
                'updateDaySheetDayNotesDto',
                'Required parameter "updateDaySheetDayNotesDto" was null or undefined when calling updateDayNotes().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/daysheet/updateDayNotes`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateDaySheetDayNotesDtoToJSON(requestParameters['updateDaySheetDayNotesDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DaySheetDtoFromJSON(jsonValue));
    }

    /**
     */
    async updateDayNotes(requestParameters: UpdateDayNotesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DaySheetDto> {
        const response = await this.updateDayNotesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
