/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateRatingDto,
  RatingDto,
} from '../models/index';
import {
    CreateRatingDtoFromJSON,
    CreateRatingDtoToJSON,
    RatingDtoFromJSON,
    RatingDtoToJSON,
} from '../models/index';

export interface CreateRatingsByDaySheetIdRequest {
    daySheetId: number;
    createRatingDto: Array<CreateRatingDto>;
}

/**
 * 
 */
export class RatingControllerApi extends runtime.BaseAPI {

    /**
     */
    async createRatingsByDaySheetIdRaw(requestParameters: CreateRatingsByDaySheetIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RatingDto>>> {
        if (requestParameters['daySheetId'] == null) {
            throw new runtime.RequiredError(
                'daySheetId',
                'Required parameter "daySheetId" was null or undefined when calling createRatingsByDaySheetId().'
            );
        }

        if (requestParameters['createRatingDto'] == null) {
            throw new runtime.RequiredError(
                'createRatingDto',
                'Required parameter "createRatingDto" was null or undefined when calling createRatingsByDaySheetId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/rating/createRatingsByDaySheetId/{daySheetId}`.replace(`{${"daySheetId"}}`, encodeURIComponent(String(requestParameters['daySheetId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['createRatingDto']!.map(CreateRatingDtoToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RatingDtoFromJSON));
    }

    /**
     */
    async createRatingsByDaySheetId(requestParameters: CreateRatingsByDaySheetIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RatingDto>> {
        const response = await this.createRatingsByDaySheetIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
