/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SystemStatusDto,
} from '../models/index';
import {
    SystemStatusDtoFromJSON,
    SystemStatusDtoToJSON,
} from '../models/index';

/**
 * 
 */
export class SystemControllerApi extends runtime.BaseAPI {

    /**
     */
    async getStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SystemStatusDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/system/status`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SystemStatusDtoFromJSON(jsonValue));
    }

    /**
     */
    async getStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SystemStatusDto> {
        const response = await this.getStatusRaw(initOverrides);
        return await response.value();
    }

}
