apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  namespace: compass-stage
  labels:
    app: postgres
spec:
  storageClassName: cinder-csi-ssd
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi