name: "Build and Push Backend Docker Image"
description: "Builds and pushes Backend Docker image to Docker Hub with dynamic tags"
inputs:
  docker_username:
    description: "Docker Hub Username"
    required: true
  docker_password:
    description: "Docker Hub Password"
    required: true
  image_tag:
    description: "Backend Docker image tag to use for the build"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}

    - name: Build and push Docker backend image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile.backend
        push: true
        tags: ${{ inputs.image_tag }}
        build-args: |
          GIT_COMMIT_ID=${{ github.sha }}
